name: herbal_tea_assistant
description: A sample ChatGPT client built with Flutter.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  # chatgpt_client: ^2.0.0
  flutter:
    sdk: flutter
  # google_fonts: ^2.1.0
  shared_preferences: ^2.0.13
  path_provider: ^2.0.7
  url_launcher: ^6.0.9 
  flutter_secure_storage: ^9.2.2
  flutter_bloc: ^8.0.1 # Check for the latest version
  equatable: ^2.0.3
  provider: ^6.0.0
  win32: ^5.0.0
  markdown_widget: ^2.0.0+1
  firebase_core: ^3.6.0
  dart_openai: ^5.1.0
  flutter_markdown: ^0.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/logo.png
    - lib/articles/
  uses-material-design: true